name: vm_app
description: "VMeste App Flutter client"
publish_to: 'none'
version: 0.1.0

environment:
  flutter: ^3.35.0
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core
  async: any
  collection: any
  meta: any
  stack_trace: any

  # State management
  control: ^0.2.0

  # Networking
  dio: ^5.9.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any # Use the pinned version from flutter_localizations

  # Storage
  shared_preferences: ^2.5.3

  # Logger
  l: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files
  generate: true

  fonts:
    # - family: AppIcons
    #   fonts:
    #     - asset: assets/fonts/AppIcons.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 400
          style: italic